// THIS FILE WAS AUTOGENERATED - ANY EDITS TO THIS WILL BE LOST WHEN IT IS REGENERATED

package sqlc



type varcharField struct {
	name string
}

type VarcharField interface {
	Field
	Eq(value string) Condition
	IsEq(value VarcharField) Condition
}

func (c *varcharField) Name() string {
	return c.name
}

func (c *varcharField) Eq(pred string) Condition {
	return Condition{Binding: FieldBinding{Value: pred, Field: c}}
}

func (c *varcharField) IsEq(pred VarcharField) Condition {
	return Condition{Binding: FieldBinding{Value: pred.Name(), Field: c}}
}

func Varchar(name string) VarcharField {
	return &varcharField{name: name}
}

